# Generated by Django 2.2.1 on 2019-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=10)),
                ('last_name', models.CharField(default='', max_length=10)),
                ('company_name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=15)),
                ('state', models.CharField(default='', max_length=15)),
                ('web', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default='', max_length=3)),
                ('zip', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
