# Generated by Django 2.2.1 on 2019-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
