# Generated by Django 2.2.1 on 2019-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190527_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='api',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
