# Generated by Django 2.2.1 on 2019-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190527_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='web',
            field=models.CharField(default='', max_length=50),
        ),
    ]
