# Generated by Django 2.2.1 on 2019-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190527_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
